### ISSUE TITLE
Transfer domain servers from Namecheap/Cloudflare to Netlify

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#197]
Ideally, the domain is handled entirely through Netlify to take advantage of their redirect domain features and it's easier in terms of permissions.

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by fvcproductions** [comment]
We will triage this in Slack instead

**Comment by Calefornia** [comment]
Would love to know what you figured out! If you could let me know what happened in the Slack discussion, much appreciated! I'm trying to use Netlify's DNS instead of Namecheap's DNS, but I can't get it to work. It appears that I'll have no choice but to use Namecheap's DNS and manually enter the records for my site and email, unless there's a better way. Thanks!!

**Comment by dvidsilva** [comment]
@Calefornia You have to go into the domain settings and change the nameserves, is not in the DNS config. 

https://www.namecheap.com/support/knowledgebase/article.aspx/767/10/how-to-change-dns-for-a-domain

Make sure all the DNS in netlify is configured correctly and so before you do the migration/change to minimize downtime.
