### ISSUE TITLE
Add additional Patreon Supporters (Round 2)

### ISSUE THREAD

**Issue by fvcproductions** [techqueria/website#303]
Update, there are now 7 supporters on Patreon - see #290 for guidelines for the first request. They should be under "Supporters" page.

Their names are:

- Frances Coronel: https://www.linkedin.com/in/fvcproductions/
- Krystal Flores: https://www.linkedin.com/in/krystalflores/
- Liliana A Monge: https://www.linkedin.com/in/lilianamonge
- Tonatiuh Ramos: https://www.linkedin.com/in/tonaramos/

---

> ✅️ By submitting this issue, I have verified the following

- [x] Checked to [see if the issue has already been discussed before](https://github.com/techqueria/website/issues) 🤔️
- [x] Made sure enough details were provided if proposing a new feature 🔍️

**Comment by sonali9696** [comment]
I would like to take a look at this.

**Comment by sonali9696** [comment]
Hi @fvcproductions, I have pushed the required changes however I wanted to discuss with you my views about the UI. According to your recent changes in CONTRIBUTING.md (https://github.com/techqueria/website/blob/master/.github/CONTRIBUTING.md#1-setting-up), under Content Updates (People), the example you have given includes role and location. This is not consistent with the existing supporters' card as a result of which it looks different in the UI.

![image](https://user-images.githubusercontent.com/12599774/55415575-e0fc7500-558a-11e9-9247-62636f64d5fc.png)

I see two solutions to this, either I can update all cards to include role and location (need clarity that from where can I get the role you have in mind and how it will be different from the description) otherwise I can remove role and location from your md file. Let me know which one you would prefer.

Also, I would like to add that 6/7 people have the same location so if we add location to the card, it would look redundant.

**Comment by fvcproductions** [comment]
@sonali9696 I can update the docs to specify that supporters should have their tier defined instead - like $10 supporter, $1 supporter, etc. - thanks so much for flagging - will keep this issue opened to address that
