### ISSUE TITLE
New Content Update Request: Differentiate Between Affiliate and Community Partners 

### ISSUE THREAD

**Issue by fvntr** [techqueria/website#687]
Currently there are affiliate partners listed as community partners. 
Since community partners are nonprofit / not-for-profit organizations, this should be updated.

**Comment by evergreen2001** [comment]
can i take this

**Comment by joelszn** [comment]
I'm guessing you want to create an affiliate partners section? Since currently there isn't one on https://techqueria.org/supporters/

Can you specify which ones?
![Screen Shot 2020-07-24 at 11 53 47 PM](https://user-images.githubusercontent.com/23111335/88448208-38ba9180-ce09-11ea-9042-3f02fc50d939.png)

**Comment by evergreen2001** [comment]
yes , springboard and code nation

**Comment by fvcproductions** [comment]
im updating this in #701

**Comment by fvntr** [comment]
ok this was updated but general assembly is a for-profit org so it should be listed under corporate partners. 
@evergreen2001 @joelszn feel free to make this change and I will close this ticket.

**Comment by fvntr** [comment]
@fvcproductions Im not finding a recent partnership agreement actually, so it is best to just remove. Can you clarify?

**Comment by fvcproductions** [comment]
i'll remove
